### ISSUE TITLE
Rabbit Source issues in CF environment

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud-stream-app-starters/rabbit#2]
When deploying Rabbit Source application in CF environment with the following configuration:

1) Rabbit Source configuration uses rabbit connection factory settings from the rabbit service that is bound to the rabbit source app
2) RabbitMessageChannelBinder that the source app uses to bind to the rabbit broker (via SCSt binder) has the rabbit connection factory settings from a rabbit source that is not bound

- When the auto-reconfiguration is `enabled`, both the rabbit `source` and the `binder` are set to use the same `rabbit connection-factory` settings configured by the auto-reconfiguration.
We'll see something like this:
```
2017-03-03T02:21:46.30+0530 [APP/PROC/WEB/0]OUT 2017-03-02 20:51:46.302  INFO 20 --- [           main] nfigurationApplicationContextInitializer : Adding cloud service auto-reconfiguration to ApplicationContext
2017-03-03T02:21:46.30+0530 [APP/PROC/WEB/0]OUT 2017-03-02 20:51:46.303  INFO 20 --- [           main] .s.a.r.s.r.RabbitSourceRabbitApplication : The following profiles are active: cloud
2017-03-03T02:21:46.31+0530 [APP/PROC/WEB/0]OUT 2017-03-02 20:51:46.309  INFO 20 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@17a87e37: startup date [Thu Mar 02 20:51:46 UTC 2017]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@18b0930f
2017-03-03T02:21:46.38+0530 [APP/PROC/WEB/0]OUT 2017-03-02 20:51:46.379  INFO 20 --- [           main] urceCloudServiceBeanFactoryPostProcessor : Auto-reconfiguring beans of type javax.sql.DataSource
2017-03-03T02:21:46.38+0530 [APP/PROC/WEB/0]OUT 2017-03-02 20:51:46.381  INFO 20 --- [           main] urceCloudServiceBeanFactoryPostProcessor : No beans of type javax.sql.DataSource found. Skipping auto-reconfiguration.
2017-03-03T02:21:46.38+0530 [APP/PROC/WEB/0]OUT 2017-03-02 20:51:46.382  INFO 20 --- [           main] bbitCloudServiceBeanFactoryPostProcessor : Auto-reconfiguring beans of type org.springframework.amqp.rabbit.connection.ConnectionFactory
2017-03-03T02:21:46.38+0530 [APP/PROC/WEB/0]OUT 2017-03-02 20:51:46.388  INFO 20 --- [           main] bbitCloudServiceBeanFactoryPostProcessor : Reconfigured bean rabbitConnectionFactory into singleton service connector CachingConnectionFactory [channelCacheSize=25, host=xxx.rmq.cloudamqp.com, port=5672, active=true org.springframework.amqp.rabbit.connection.CachingConnectionFactory@6cfcd46d]
```

- When the auto-reconfiguration is disabled, both the rabbit `source` and the `binder` are configured to use the appropriate rabbit connection factory based on the properties set. But, the following exception is thrown at the app startup:

```
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT 2017-03-02 20:41:38.086  WARN 18 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : Failed to declare binding: Binding [destination=ilaya-test.rl, exchange=ilaya-test, routingKey=ilaya-test], continuing...
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT org.springframework.amqp.AmqpIOException: java.io.IOException
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:71) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:309) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:547) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:1387) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1368) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1344) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.amqp.rabbit.core.RabbitAdmin.declareBinding(RabbitAdmin.java:292) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.declareBinding(RabbitMessageChannelBinder.java:488) [spring-cloud-stream-binder-rabbit-1.1.1.RELEASE.jar!/:1.1.1.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.createProducerMessageHandler(RabbitMessageChannelBinder.java:384) [spring-cloud-stream-binder-rabbit-1.1.1.RELEASE.jar!/:1.1.1.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.createProducerMessageHandler(RabbitMessageChannelBinder.java:85) [spring-cloud-stream-binder-rabbit-1.1.1.RELEASE.jar!/:1.1.1.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:101) [spring-cloud-stream-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:53) [spring-cloud-stream-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:148) [spring-cloud-stream-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.cloud.stream.binding.ChannelBindingService.bindProducer(ChannelBindingService.java:113) [spring-cloud-stream-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.cloud.stream.binding.BindableProxyFactory.bindOutputs(BindableProxyFactory.java:208) [spring-cloud-stream-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:57) [spring-cloud-stream-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173) [spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346) [spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51) [spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149) [spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112) [spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:874) [spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) [spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.cloud.stream.app.rabbit.source.rabbit.RabbitSourceRabbitApplication.main(RabbitSourceRabbitApplication.java:29) [classes/:na]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app/:na]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app/:na]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app/:na]
2017-03-03T02:11:38.08+0530 [APP/PROC/WEB/0]OUT     at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [app/:na]


2017-03-03T02:28:21.33+0530 [APP/PROC/WEB/0]OUT 2017-03-02 20:58:21.332  INFO 20 --- [    container-9] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer: tags=[{}], channel=null, acknowledgeMode=AUTO local queue size=0
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 2017-03-02 20:58:26.351  WARN 20 --- [   container-10] o.s.a.r.l.SimpleMessageListenerContainer : Consumer raised exception, processing can restart if the connection factory supports it
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT org.springframework.amqp.AmqpIOException: java.io.IOException
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:71) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:309) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:547) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$1.createConnection(ConnectionFactoryUtils.java:90) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.doGetTransactionalResourceHolder(ConnectionFactoryUtils.java:140) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:76) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:472) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1280) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT Caused by: java.io.IOException: null
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:106) ~[amqp-client-3.6.3.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:102) ~[amqp-client-3.6.3.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:350) ~[amqp-client-3.6.3.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:813) ~[amqp-client-3.6.3.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:725) ~[amqp-client-3.6.3.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:296) ~[spring-rabbit-1.6.2.RELEASE.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	... 7 common frames omitted
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT Caused by: com.rabbitmq.client.ShutdownSignalException: connection error
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:67) ~[amqp-client-3.6.3.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:37) ~[amqp-client-3.6.3.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:367) ~[amqp-client-3.6.3.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:293) ~[amqp-client-3.6.3.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	... 10 common frames omitted
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT Caused by: java.io.EOFException: null
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290) ~[na:1.8.0_121]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:95) ~[amqp-client-3.6.3.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:139) ~[amqp-client-3.6.3.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:542) ~[amqp-client-3.6.3.jar!/:na]
2017-03-03T02:28:26.35+0530 [APP/PROC/WEB/0]OUT 	... 1 common frames omitted
```

**Comment by garyrussell** [comment]
@ilayaperumalg What are you setting the rabbit credentials to in the second case (when you are not using cloud reconfig) ?

**Comment by garyrussell** [comment]
IIRC, if you don't use cloud reconfig, you have to get the credentials from the vcap properties.@ilayaperumalg What are you setting the rabbit credentials to in the second case (when you are not using cloud reconfig) ?

IIRC, if you don't use cloud reconfig, you have to get the credentials from the vcap properties.

Oh, I see; it looks like he's having issues connecting to an external broker - is that what you tried too? Have you looked at the server logs as I suggested?

**Comment by ilayaperumalg** [comment]
> it looks like he's having issues connecting to an external broker - is that what you tried too? Have you looked at the server logs as I suggested?

yeah, I tried the same thing. I couldn't get access to the rabbit service log though. I set the credentials via SPRING_APPLICATION_JSON property that is set for the rabbit source app.

**Comment by sabbyanandan** [comment]
It has been identified that we had the wrong port that caused these errors. This issue is not relevant anymore. The parent thread is still active, though.
